"use strict";
exports.__esModule = true;
var cel_1 = require("./cel");
var rapport_1 = require("./rapport");
var rekenblad_1 = require("./rekenblad");
var terminalprinter_1 = require("./terminalprinter");
var c = new cel_1.cel('A', 1, '105 euro');
var c2 = new cel_1.cel('A', 2, '205 euro');
var c3 = new cel_1.cel('A', 3, '255 euro');
var test = new rekenblad_1.rekenblad('Pagina 1');
var arr = [c, c2, c3];
test.setInhoud([c, c2, c3]);
console.log(test.GeefTeDrukkentxt());
var rapport = new rapport_1.Rapport();
rapport.ZetTitel("Nieuw Rapport");
rapport.ZetInhoud("Dit rapport moet gaan over ....");
console.log(rapport.GeefTeDrukkentxt());
var ts = new terminalprinter_1.terminalprinter();
ts.afdrukken(rapport);
ts.afdrukken(test);
